### ISSUE TITLE
Delete button not showing on github page

### ISSUE THREAD

**Issue by aaanx** [aaanx/Budgety_App#5]
When I open the page directly from my computer I can see that after hover on exp/inc **delete button** is appearing. On the github page there is a blank spot. Why is that?

After hover it should look like this:
![delete_btn](https://user-images.githubusercontent.com/46420347/56676905-92408780-66bf-11e9-881e-b33b166fea09.png)

**Comment by roottool** [comment]
This reason is the page has occurred an error when a stylesheet is read.
![ConsoleError](https://user-images.githubusercontent.com/11808736/56687836-1b80aa00-6712-11e9-99a0-8be64bcfff6a.jpg)
This error message said `the content must be served over HTTPS`.
Therefore, you have to convert from `http` to `https` in the below.
https://github.com/aaanx/Budgety_App/blob/0172467831c4863a1255438c102954b676c7678e/index.html#L6

**Comment by aaanx** [comment]
Hey, it worked. Thank you for your help.
